# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lyricfy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs_number',
        ),
        migrations.RemoveField(
            model_name='song',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
    ]
