# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lyricfy_app', '0002_auto_20180525_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='authors',
            new_name='author',
        ),
    ]
