# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lyricfy_app', '0003_auto_20180525_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
