# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 01:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lyricfy_app', '0004_auto_20180525_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='Album', to='lyricfy_app.Album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autor',
                                    to='lyricfy_app.Author', unique=True),
        ),
    ]
