# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lyricfy_app', '0005_auto_20180420_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='launch_date',
        ),
    ]
