# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lyricfy_app', '0005_auto_20180420_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(related_name='Album', to='lyricfy_app.Album'),
        ),
    ]
