# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lyricfy_app', '0006_auto_20180526_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
    ]
