# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lyricfy_app', '0006_auto_20180420_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lyrics',
            new_name='Lyric',
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(related_name='Cantant', to='lyricfy_app.Author'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='Album', to='lyricfy_app.Album'),
        ),
    ]
