# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 01:22
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lyricfy_app', '0007_remove_song_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autor',
                                    to='lyricfy_app.Author'),
        ),
    ]
